// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrkhnpajcalpdfjvqyes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxya2hucGFqY2FscGRmanZxeWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODM4NTAsImV4cCI6MjA3NDE1OTg1MH0.sT7OFNHGzpuLPUiFJRHMToWbue70kEOIB0ykhNcmoQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});